import{a as b,S as w,i as n}from"./assets/vendor-BgmC94F3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const S="https://pixabay.com/api/",v="53020322-8236fb03113a5119ee0fdb502";async function f(s,r=1){try{const e={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await b.get(S,{params:e})).data}catch(e){throw console.error("❌ Error fetching images:",e),e}}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");let q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const r=s.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){h.innerHTML=""}function y(){m.classList.remove("is-hidden")}function i(){m.classList.add("is-hidden")}function P(){p.classList.remove("is-hidden")}function d(){p.classList.add("is-hidden")}const R=document.querySelector(".form"),B=document.querySelector(".load-more");let a=1,u="",L=0;R.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}u=r,a=1,E(),d(),y();try{const e=await f(u,a);if(i(),L=e.totalHits,e.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),e.totalHits>a*15?P():d()}catch(e){i(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}});B.addEventListener("click",async()=>{a+=1,y();try{const s=await f(u,a);i(),g(s.hits);const r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),a*15>=L&&(d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
